/* Generated By:JavaCC: Do not edit this line. RRule10SyntaxParserConstants.java */
package com.funambol.common.pim.xvcalendar.rrule;

public interface RRule10SyntaxParserConstants {

  int EOF = 0;
  int DIGITS = 16;
  int PLUS = 17;
  int MINUS = 18;
  int ISO_8601_DATE_TIME = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"D\"",
    "\"W\"",
    "\"MP\"",
    "\"MD\"",
    "\"YM\"",
    "\"YD\"",
    "\"SU\"",
    "\"MO\"",
    "\"TU\"",
    "\"WE\"",
    "\"TH\"",
    "\"FR\"",
    "\"SA\"",
    "\"LD\"",
    "\"#\"",
    "<DIGITS>",
    "\"+\"",
    "\"-\"",
    "<ISO_8601_DATE_TIME>",
    "<token of kind 20>",
  };

}
