/* Generated By:JavaCC: Do not edit this line. XVCalendarSyntaxParserConstants.java */
package com.funambol.common.pim.xvcalendar;

public interface XVCalendarSyntaxParserConstants {

  int EOF = 0;
  int BEGIN_VCAL_T = 1;
  int BEGIN_VEVENT_T = 2;
  int BEGIN_VTODO_T = 3;
  int END_VCAL_T = 4;
  int END_VEVENT_T = 5;
  int END_VTODO_T = 6;
  int WS_T = 7;
  int CRLF_T = 8;
  int SEMICOLON_T = 9;
  int EQUALS_T = 10;
  int PARAMETER_T = 11;
  int QP_PARAMETER_T = 12;
  int PARAM_LINEFOLD_T = 13;
  int IDENTIFIER_T = 14;
  int COLON_T = 15;
  int COLON_T_QP = 16;
  int PROP_VALUE_T = 17;
  int PROP_LINEFOLD_T = 18;
  int PROP_VALUE_T_QP = 19;
  int PROP_EXCEPTIONS_T_QP = 20;
  int PROP_LINEFOLD_T_QP = 21;
  int PROP_EXCEPTIONS_SPLIT_T_1_QP = 22;
  int PROP_EXCEPTIONS_SPLIT_T_2_QP = 23;

  int DEFAULT = 0;
  int PROP_VALUE_STATE_QP = 1;
  int PROP_VALUE_STATE = 2;
  int PARAMLIST_WITH_QP_STATE = 3;
  int PARAMLIST_STATE = 4;

  String[] tokenImage = {
    "<EOF>",
    "\"BEGIN:VCALENDAR\"",
    "\"BEGIN:VEVENT\"",
    "\"BEGIN:VTODO\"",
    "\"END:VCALENDAR\"",
    "\"END:VEVENT\"",
    "\"END:VTODO\"",
    "<WS_T>",
    "<CRLF_T>",
    "\";\"",
    "\"=\"",
    "<PARAMETER_T>",
    "<QP_PARAMETER_T>",
    "<PARAM_LINEFOLD_T>",
    "<IDENTIFIER_T>",
    "\":\"",
    "\":\"",
    "<PROP_VALUE_T>",
    "<PROP_LINEFOLD_T>",
    "<PROP_VALUE_T_QP>",
    "<PROP_EXCEPTIONS_T_QP>",
    "<PROP_LINEFOLD_T_QP>",
    "<PROP_EXCEPTIONS_SPLIT_T_1_QP>",
    "<PROP_EXCEPTIONS_SPLIT_T_2_QP>",
  };

}
