/* Generated By:JavaCC: Do not edit this line. VCardSyntaxParserConstants.java */
package com.funambol.common.pim.vcard;

public interface VCardSyntaxParserConstants {

  int EOF = 0;
  int EOL = 2;
  int SEOL = 3;
  int SEOL_QP = 4;
  int COLON = 5;
  int COLON_QP = 6;
  int SEMICOLON = 7;
  int SEMICOLON_QP = 8;
  int EQUAL = 9;
  int CATEGORIES = 10;
  int VERSION = 11;
  int TITLE = 12;
  int NICKNAME = 13;
  int EMAIL = 14;
  int FN = 15;
  int ORG = 16;
  int BDAY = 17;
  int PHOTO = 18;
  int ADR = 19;
  int UID = 20;
  int LABEL = 21;
  int ROLE = 22;
  int TZ = 23;
  int LOGO = 24;
  int NOTE = 25;
  int URL = 26;
  int N = 27;
  int REV = 28;
  int TEL = 29;
  int FBURL = 30;
  int CLASS = 31;
  int GEO = 32;
  int MAILER = 33;
  int IMPP = 34;
  int AGENT = 35;
  int PRODID = 36;
  int KEY = 37;
  int FOLDER = 38;
  int ANNIVERSARY = 39;
  int CHILDREN = 40;
  int COMPANIES = 41;
  int LANGUAGES = 42;
  int MANAGER = 43;
  int MILEAGE = 44;
  int SPOUSE = 45;
  int SUBJECT = 46;
  int VCBEGIN = 47;
  int VCEND = 48;
  int EXTENSION = 49;
  int CONTENTSTRING = 50;
  int CONTENTSTRING_QP = 51;
  int NONBREAKINGEQUALS = 52;
  int WS = 53;
  int QUOTED_PRINTABLE = 54;
  int PARAMSTRING = 55;
  int IDENTIFIER = 56;

  int DEFAULT = 0;
  int CONTENTSTATE = 1;
  int CONTENTSTATE_QP = 2;
  int PARAMSTATE = 3;
  int PARAMSTATE_QP = 4;

  String[] tokenImage = {
    "<EOF>",
    "\".\"",
    "<EOL>",
    "<SEOL>",
    "<SEOL_QP>",
    "\":\"",
    "\":\"",
    "\";\"",
    "\";\"",
    "\"=\"",
    "\"CATEGORIES\"",
    "\"VERSION\"",
    "\"TITLE\"",
    "\"NICKNAME\"",
    "\"EMAIL\"",
    "\"FN\"",
    "\"ORG\"",
    "\"BDAY\"",
    "\"PHOTO\"",
    "\"ADR\"",
    "\"UID\"",
    "\"LABEL\"",
    "\"ROLE\"",
    "\"TZ\"",
    "\"LOGO\"",
    "\"NOTE\"",
    "\"URL\"",
    "\"N\"",
    "\"REV\"",
    "\"TEL\"",
    "\"FBURL\"",
    "\"CLASS\"",
    "\"GEO\"",
    "\"MAILER\"",
    "\"IMPP\"",
    "\"AGENT\"",
    "\"PRODID\"",
    "\"KEY\"",
    "\"X-FUNAMBOL-FOLDER\"",
    "\"X-ANNIVERSARY\"",
    "\"X-FUNAMBOL-CHILDREN\"",
    "\"X-FUNAMBOL-COMPANIES\"",
    "\"X-FUNAMBOL-LANGUAGES\"",
    "\"X-MANAGER\"",
    "\"X-FUNAMBOL-MILEAGE\"",
    "\"X-SPOUSE\"",
    "\"X-FUNAMBOL-SUBJECT\"",
    "<VCBEGIN>",
    "<VCEND>",
    "<EXTENSION>",
    "<CONTENTSTRING>",
    "<CONTENTSTRING_QP>",
    "\"=\"",
    "<WS>",
    "<QUOTED_PRINTABLE>",
    "<PARAMSTRING>",
    "<IDENTIFIER>",
  };

}
